Advantages of Numpy:
1. Allows Multiple operation 
2. Faster Operations


In [ ]:
import numpy as np

#one D array
a = np.array([1,2,3,4])

a.shape

#2D array
two_d = np.array([(1,2,3),(3,4,5)])

# definig data type
c = np.array([(1,2,3),(3,4,5),(4,5,6)], dtype = float)
print(c)


[[1. 2. 3.]
 [3. 4. 5.]
 [4. 5. 6.]]


In [ ]:
# arrays with one particular value

a = np.zeros((3,3))
print(a)

b = np.ones((4,5))
print(b)

c = np.full((5,6), 2)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]]


In [ ]:
# creating identity matriex

a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# create array with random vals

b = np.random.random((3,4)) # all the vals will from 0 to 1
print(b)

c = np.random.randint(10,100,(4,5)) # (start, end, shape)
print(c)



[[0.27798318 0.22407984 0.79624901 0.98501109]
 [0.93605106 0.54273588 0.4336268  0.67825692]
 [0.56084154 0.08000746 0.00133479 0.13766309]]
[[49 45 20 86 94]
 [52 56 99 36 89]
 [86 10 72 47 18]
 [22 73 67 24 99]]
[1 3]


In [ ]:
# creating array of evenly spaced values --> specifying the value number

a = np.linspace(10,50,5) #(start, end, number_of_vals)
print(a)

# creating array of evenly spaced values --> specifying the step

b = np.arange(10,40,4.5)
print(b)

[10. 20. 30. 40. 50.]
[10.  14.5 19.  23.5 28.  32.5 37. ]


In [ ]:
# converting a list to a numpy array
list_one = [1,2,3,4,5,6,7]

np_array = np.asarray(list_one)
print(np_array)

[1 2 3 4 5 6 7]


Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

print(c.shape) # returns rows and cloumns
print(c.ndim) # returns dimension
print(c.size) # value count
c.dtype # returns data type

[[65 18 59 36 21]
 [47 44 18 34 11]
 [71 21 61 42 57]
 [73 80 31 89 82]
 [23 54 38 29 50]]
(5, 5)
2
25


dtype('int64')

#Math Operations

In [ ]:
x = np.random.randint(10,30,(3,3))
y = np.random.randint(30,50,(3,3))
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[[69 55 68]
 [63 60 60]
 [64 48 66]]
[[-29 -19 -10]
 [-25  -4 -14]
 [-32 -16 -18]]
[[ 980  666 1131]
 [ 836  896  851]
 [ 768  512 1008]]
[[0.40816327 0.48648649 0.74358974]
 [0.43181818 0.875      0.62162162]
 [0.33333333 0.5        0.57142857]]


#Array Manipulation

In [ ]:
c = np.random.randint(10,50,(2,3))
print(c)

trans = np.transpose(c)
print(trans)

d = np.random.randint(10,50,(2,3))
print(d)
trans_one = d.T
print(trans_one)


[[27 39 29]
 [19 37 16]]
[[27 19]
 [39 37]
 [29 16]]
[[48 13 48]
 [20 45 24]]
[[48 20]
 [13 45]
 [48 24]]
